### ISSUE TITLE
Please remove the CNAME

### ISSUE THREAD

**Issue by BallinBallen** [dc207/dc207.github.io#1]
Hi Casey,

Please remove the CNAME for DC207.org. The group is being revived, and we would like to use github to host, and we cannot if you have a CNAME already registered. We have registered the domain, and in good faith, we have tried contacting you. We decided to move on and revive the group after not hearing back from you via e-mail or LinkedIn.

**Comment by caseydunham** [comment]
Hey, sorry about that. I'll remove the CNAME for you.

**Comment by caseydunham** [comment]
I also invited you to the dc207 organization, as I'd like to fully transfer that away. Please email me at casey[at]caseydunham.com!

Thanks!
